window.FORMA_CATALOG = [
  {
    id: "12",
    name: "Sofá Colombo",
    category: "Sala",
    description:
      "Líneas amplias, textura cálida y un asiento generoso. El centro de las conversaciones en casa.",
    price: 4499982,
    stock: 12,
    images: ["assets/products/12/1.webp", "assets/products/12/2.webp", "assets/products/12/3.webp"],
    featured: true,
    material: "Madera y acabados mixtos",
    sourceId: 12,
  },
  {
    id: "14",
    name: "Silla Saarinen",
    category: "Estudio",
    description:
      "Una pieza de perfil ligero para acompañar tu mesa de trabajo o tu próxima sobremesa.",
    price: 899982,
    stock: 12,
    images: ["assets/products/14/1.webp", "assets/products/14/2.webp", "assets/products/14/3.webp"],
    featured: true,
    material: "Madera y acabados mixtos",
    sourceId: 14,
  },
  {
    id: "46",
    name: "Maceta Terra",
    category: "Objetos",
    description: "Una forma sencilla para acompañar tus plantas y dar vida a tu espacio.",
    price: 26982,
    stock: 12,
    images: [
      "assets/products/46/1.webp",
      "assets/products/46/2.webp",
      "assets/products/46/3.webp",
      "assets/products/46/4.webp",
    ],
    featured: true,
    material: "Acabados decorativos",
    sourceId: 46,
  },
  {
    id: "47",
    name: "Lámpara Table",
    category: "Iluminación",
    description: "Luz de acento para acompañar la lectura y darle otro ritmo a tus tardes.",
    price: 89982,
    stock: 9,
    images: ["assets/products/47/1.webp"],
    featured: true,
    material: "Acabados decorativos",
    sourceId: 47,
  },
  {
    id: "11",
    name: "Cama Colombo",
    category: "Dormitorio",
    description:
      "Una silueta envolvente en madera y tapizado para convertir el dormitorio en tu lugar favorito.",
    price: 3419982,
    stock: 12,
    images: ["assets/products/11/1.webp", "assets/products/11/2.webp", "assets/products/11/3.webp"],
    featured: false,
    material: "Madera y acabados mixtos",
    sourceId: 11,
  },
  {
    id: "13",
    name: "Mesa lateral Cherry",
    category: "Sala",
    description:
      "Un acento de madera junto a tu sillón. Espacio para un libro, una taza y los pequeños rituales.",
    price: 539982,
    stock: 12,
    images: ["assets/products/13/1.webp", "assets/products/13/2.webp", "assets/products/13/3.webp"],
    featured: false,
    material: "Madera y acabados mixtos",
    sourceId: 13,
  },
  {
    id: "15",
    name: "Mueble de baño Wood",
    category: "Baño",
    description: "Almacenamiento y espejo en una composición de madera que ordena tus rutinas.",
    price: 1439982,
    stock: 7,
    images: ["assets/products/15/1.webp", "assets/products/15/2.webp", "assets/products/15/3.webp"],
    featured: false,
    material: "Madera y acabados mixtos",
    sourceId: 15,
  },
  {
    id: "43",
    name: "Colgante Balance",
    category: "Objetos",
    description: "Un pequeño detalle suspendido para añadir movimiento a tu rincón favorito.",
    price: 107982,
    stock: 12,
    images: ["assets/products/43/1.webp", "assets/products/43/2.webp", "assets/products/43/3.webp"],
    featured: false,
    material: "Acabados decorativos",
    sourceId: 43,
  },
  {
    id: "44",
    name: "Marco Family",
    category: "Objetos",
    description:
      "Tus recuerdos encuentran su lugar en una composición pensada para tenerlos cerca.",
    price: 53982,
    stock: 12,
    images: ["assets/products/44/1.webp"],
    featured: false,
    material: "Acabados decorativos",
    sourceId: 44,
  },
  {
    id: "45",
    name: "Planta House",
    category: "Objetos",
    description: "Un toque de verde para vestir repisas, escritorios y mesas auxiliares.",
    price: 71982,
    stock: 12,
    images: ["assets/products/45/1.webp", "assets/products/45/2.webp", "assets/products/45/3.webp"],
    featured: false,
    material: "Acabados decorativos",
    sourceId: 45,
  },
];
